Resources:
  GetEnviosPendientes:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/getEnviosPendientes.handler
      Runtime: nodejs14.x
      Events:
        GetEnviosPendientes:
          Type: Api
          Properties:
            Path: /envios/pendientes
            Method: GET
  PostEnvio:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/postEnvio.handler
      Runtime: nodejs14.x
      Events:
        PostEnvio:
          Type: Api
          Properties:
            Path: /envios
            Method: POST
